import type { Metadata } from "next";
import { Navbar } from "@/components/layout/navbar";
import { Footer } from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How ReviewLens collects, uses, and protects your data.",
};

export default function PrivacyPage() {
  return (
    <div className="flex min-h-screen flex-col">
      <Navbar />

      <main className="container max-w-2xl flex-1 py-16 md:py-20">
        <h1 className="text-report-h1">Privacy Policy</h1>

        <p className="mt-2 text-xs text-muted-foreground">
          Last updated June 17, 2026
        </p>

        <div className="mt-10 space-y-8">
          <section>
            <h2 className="text-sm font-semibold">Overview</h2>

            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              ReviewLens analyzes customer review data and generates
              AI-powered insights, sentiment analysis, and summaries.
              This page explains what data is collected, how it is used,
              and how it is protected.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold">What we collect</h2>

            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              When you upload a CSV file, we store the review content and any
              information contained within that file, such as ratings, review
              dates, and product-related metadata. ReviewLens does not require
              an account and does not collect names, passwords, or other
              personal profile information.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold">How your data is used</h2>

            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              Uploaded review data is processed to identify themes, sentiment,
              and patterns. The system generates embeddings and AI-powered
              summaries to create reports and visual insights automatically.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold">
              Third-party processing
            </h2>

            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              Review data may be processed through OpenAI APIs to generate
              embeddings, classifications, and summaries. OpenAI handles data
              according to its own policies and terms.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold">Shareable reports</h2>

            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              Reports may be accessible through unique links generated by
              ReviewLens. Anyone with access to a report link may be able to
              view that report. Avoid uploading sensitive, confidential, or
              personally identifiable information.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold">Deleting your data</h2>

            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              You may delete an analysis at any time. Once deleted, the
              uploaded review data and generated report are permanently
              removed and cannot be recovered.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold">Cookies and analytics</h2>

            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              ReviewLens does not currently use advertising trackers or
              third-party analytics tools. If analytics are introduced in
              the future, this policy will be updated accordingly.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold">
              Changes to this policy
            </h2>

            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              This privacy policy may be updated periodically as ReviewLens
              evolves. Updates will be reflected by the date shown at the
              top of this page.
            </p>
          </section>

          <section>
            <h2 className="text-sm font-semibold">Questions</h2>

            <p className="mt-2 text-sm leading-relaxed text-muted-foreground">
              If you have questions regarding this privacy policy or how
              data is handled, please contact the ReviewLens team.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
