import type { StoredAnalysisResult } from "@/features/analysis/types";

interface BuildPdfOptions {
  result: StoredAnalysisResult;
  totalReviews: number;
  title: string;
  fileName: string;
}

const BRAND = { r: 79, g: 70, b: 229 }; // indigo-600

// Dynamically imported so jsPDF (~150kb) stays out of the main bundle.
export async function buildAnalysisPdf({
  result,
  totalReviews,
  title,
  fileName,
}: BuildPdfOptions): Promise<void> {
  const { jsPDF } = await import("jspdf");
  const autoTable = (await import("jspdf-autotable")).default;

  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;
  const contentWidth = pageWidth - margin * 2;

  // ── Header band ──────────────────────────────────────────────────────────
  doc.setFillColor(BRAND.r, BRAND.g, BRAND.b);
  doc.rect(0, 0, pageWidth, 70, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("ReviewLens", margin, 34);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.text("Customer review analysis report", margin, 52);
  doc.setFontSize(9);
  doc.text(
    new Date().toLocaleDateString(undefined, {
      year: "numeric",
      month: "long",
      day: "numeric",
    }),
    pageWidth - margin,
    52,
    { align: "right" }
  );

  let y = 96;

  // ── Title ────────────────────────────────────────────────────────────────
  doc.setTextColor(17, 24, 39);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text(title, margin, y);
  y += 22;

  // ── Stat line ──────────────────────────────────────────────────────────────
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(75, 85, 99);
  const stats = [
    `${totalReviews.toLocaleString()} reviews`,
    `${result.themes.length} themes`,
    result.averageRating ? `${result.averageRating.toFixed(1)}/5 avg` : null,
    `${(result.processingMs / 1000).toFixed(1)}s processing`,
  ]
    .filter(Boolean)
    .join("    •    ");
  doc.text(stats, margin, y);
  y += 24;

  // ── Executive summary ──────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(17, 24, 39);
  doc.text("Executive summary", margin, y);
  y += 16;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(55, 65, 81);
  const summaryLines = doc.splitTextToSize(
    result.executiveSummary,
    contentWidth
  );
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 13 + 16;

  // ── Sentiment breakdown ────────────────────────────────────────────────────
  const sb = result.sentimentBreakdown;
  autoTable(doc, {
    startY: y,
    head: [["Sentiment", "Positive", "Negative", "Neutral", "Mixed"]],
    body: [
      [
        "Reviews",
        String(sb.positive),
        String(sb.negative),
        String(sb.neutral),
        String(sb.mixed),
      ],
    ],
    margin: { left: margin, right: margin },
    headStyles: { fillColor: [BRAND.r, BRAND.g, BRAND.b], fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    theme: "grid",
  });

  // @ts-expect-error lastAutoTable is added by the plugin at runtime
  y = (doc.lastAutoTable?.finalY ?? y) + 22;

  // ── Themes table ───────────────────────────────────────────────────────────
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(17, 24, 39);
  doc.text("Themes", margin, y);
  y += 8;

  const themeBody = [...result.themes]
    .sort((a, b) => b.reviewCount - a.reviewCount)
    .map((t) => [
      t.label,
      t.sentiment,
      String(t.reviewCount),
      `${t.percentage.toFixed(1)}%`,
      t.description,
    ]);

  autoTable(doc, {
    startY: y + 6,
    head: [["Theme", "Sentiment", "Reviews", "%", "Description"]],
    body: themeBody,
    margin: { left: margin, right: margin },
    headStyles: { fillColor: [BRAND.r, BRAND.g, BRAND.b], fontSize: 9 },
    bodyStyles: { fontSize: 9, valign: "top" },
    columnStyles: {
      0: { cellWidth: 110, fontStyle: "bold" },
      1: { cellWidth: 60 },
      2: { cellWidth: 50, halign: "right" },
      3: { cellWidth: 40, halign: "right" },
      4: { cellWidth: "auto" },
    },
    theme: "striped",
  });

  // ── Footer page numbers ────────────────────────────────────────────────────
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(156, 163, 175);
    doc.text(
      `Generated by ReviewLens · Page ${i} of ${pageCount}`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 20,
      { align: "center" }
    );
  }

  doc.save(fileName);
}
